from tkinter import *

root = Tk()
root.geometry("600x600")
root.title("Welcome To Ithuba Lotto")
root.config(bg="#FFC107")

lotto_logo = PhotoImage(file="images/loto logo 1.png")
ithuba_logo = PhotoImage(file="images/ithuba.PNG")

# place image
canvas = Canvas(root, width=270, height=180, highlightthickness="0") #
canvas.create_image(0, 0, anchor=NW, image=lotto_logo,)
canvas.place(x=165, y=10)

canvas = Canvas(root, width=178, height=55, highlightthickness="0") #
canvas.create_image(0, 0, anchor=NW, image=ithuba_logo,)
canvas.place(x=400, y=520)


number_1 = PhotoImage(file="images/buttons/1.png")
number_2 = PhotoImage(file="images/buttons/2.png")
number_3 = PhotoImage(file="images/buttons/3.png")
number_4 = PhotoImage(file="images/buttons/4.png")
number_5 = PhotoImage(file="images/buttons/5.png")
number_6 = PhotoImage(file="images/buttons/6.png")
number_7 = PhotoImage(file="images/buttons/7.png")
number_8 = PhotoImage(file="images/buttons/8.png")
number_9 = PhotoImage(file="images/buttons/9.png")
number_10 = PhotoImage(file="images/buttons/10.png")
number_11 = PhotoImage(file="images/buttons/11.png")
number_12 = PhotoImage(file="images/buttons/12.png")
number_13 = PhotoImage(file="images/buttons/13.png")
number_14 = PhotoImage(file="images/buttons/14.png")
number_15 = PhotoImage(file="images/buttons/15.png")
number_16 = PhotoImage(file="images/buttons/16.png")
number_17 = PhotoImage(file="images/buttons/17.png")
number_18 = PhotoImage(file="images/buttons/18.png")
number_19 = PhotoImage(file="images/buttons/19.png")
number_20 = PhotoImage(file="images/buttons/20.png")
number_21 = PhotoImage(file="images/buttons/21.png")
number_22 = PhotoImage(file="images/buttons/22.png")
number_23 = PhotoImage(file="images/buttons/23.png")
number_24 = PhotoImage(file="images/buttons/24.png")
number_25 = PhotoImage(file="images/buttons/25.png")
number_26 = PhotoImage(file="images/buttons/26.png")
number_27 = PhotoImage(file="images/buttons/27.png")
number_28 = PhotoImage(file="images/buttons/28.png")
number_29 = PhotoImage(file="images/buttons/29.png")
number_30 = PhotoImage(file="images/buttons/30.png")
# number_31 = PhotoImage(file="images/buttons/31.png")
# number_32 = PhotoImage(file="images/buttons/32.png")
# number_33 = PhotoImage(file="images/buttons/33.png")
# number_34 = PhotoImage(file="images/buttons/34.png")
# number_35 = PhotoImage(file="images/buttons/35.png")
# number_36 = PhotoImage(file="images/buttons/36.png")
# number_37 = PhotoImage(file="images/buttons/37.png")
# number_38 = PhotoImage(file="images/buttons/38.png")
# number_39 = PhotoImage(file="images/buttons/39.png")
# number_40 = PhotoImage(file="images/buttons/40.png")

numb_label = Label(image=number_1)


def choose_number():
    my_label.config(text="1")


btn_1 = Button(root, image=number_1, command=choose_number, borderwidth=0, highlightthickness=0, highlightbackground="#FFC107", bd=0, bg="#FFC107")
btn_1.place(x=50, y=200)
btn_2 = Button(root, image=number_2, command=choose_number, borderwidth=0, highlightthickness=0, highlightbackground="#FFC107", bd=0, bg="#FFC107")
btn_2.place(x=100, y=200)
btn_3 = Button(root, image=number_3, command=choose_number, borderwidth=0, highlightthickness=0, highlightbackground="#FFC107", bd=0, bg="#FFC107")
btn_3.place(x=150, y=200)
btn_4 = Button(root, image=number_4, command=choose_number, borderwidth=0, highlightthickness=0, highlightbackground="#FFC107", bd=0, bg="#FFC107")
btn_4.place(x=200, y=200)
btn_5 = Button(root, image=number_5, command=choose_number, borderwidth=0, highlightthickness=0, highlightbackground="#FFC107", bd=0, bg="#FFC107")
btn_5.place(x=250, y=200)
btn_6 = Button(root, image=number_6, command=choose_number, borderwidth=0, highlightthickness=0, highlightbackground="#FFC107", bd=0, bg="#FFC107")
btn_6.place(x=300, y=200)
btn_7 = Button(root, image=number_7, command=choose_number, borderwidth=0, highlightthickness=0, highlightbackground="#FFC107", bd=0, bg="#FFC107")
btn_7.place(x=350, y=200)
btn_8 = Button(root, image=number_8, command=choose_number, borderwidth=0, highlightthickness=0, highlightbackground="#FFC107", bd=0, bg="#FFC107")
btn_8.place(x=400, y=200)
btn_9 = Button(root, image=number_9, command=choose_number, borderwidth=0, highlightthickness=0, highlightbackground="#FFC107", bd=0, bg="#FFC107")
btn_9.place(x=450, y=200)
btn_10 = Button(root, image=number_10, command=choose_number, borderwidth=0, highlightthickness=0, highlightbackground="#FFC107", bd=0, bg="#FFC107")
btn_10.place(x=500, y=200)
btn_11 = Button(root, image=number_11, command=choose_number, borderwidth=0, highlightthickness=0, highlightbackground="#FFC107", bd=0, bg="#FFC107")
btn_11.place(x=50, y=250)
btn_12 = Button(root, image=number_12, command=choose_number, borderwidth=0, highlightthickness=0, highlightbackground="#FFC107", bd=0, bg="#FFC107")
btn_12.place(x=100, y=250)
btn_13 = Button(root, image=number_13, command=choose_number, borderwidth=0, highlightthickness=0, highlightbackground="#FFC107", bd=0, bg="#FFC107")
btn_13.place(x=150, y=250)
btn_14 = Button(root, image=number_14, command=choose_number, borderwidth=0, highlightthickness=0, highlightbackground="#FFC107", bd=0, bg="#FFC107")
btn_14.place(x=200, y=250)
btn_15 = Button(root, image=number_15, command=choose_number, borderwidth=0, highlightthickness=0, highlightbackground="#FFC107", bd=0, bg="#FFC107")
btn_15.place(x=250, y=250)
btn_16 = Button(root, image=number_16, command=choose_number, borderwidth=0, highlightthickness=0, highlightbackground="#FFC107", bd=0, bg="#FFC107")
btn_16.place(x=300, y=250)
btn_17 = Button(root, image=number_17, command=choose_number, borderwidth=0, highlightthickness=0, highlightbackground="#FFC107", bd=0, bg="#FFC107")
btn_17.place(x=350, y=250)
btn_18 = Button(root, image=number_18, command=choose_number, borderwidth=0, highlightthickness=0, highlightbackground="#FFC107", bd=0, bg="#FFC107")
btn_18.place(x=400, y=250)
btn_19 = Button(root, image=number_19, command=choose_number, borderwidth=0, highlightthickness=0, highlightbackground="#FFC107", bd=0, bg="#FFC107")
btn_19.place(x=450, y=250)
btn_20 = Button(root, image=number_20, command=choose_number, borderwidth=0, highlightthickness=0, highlightbackground="#FFC107", bd=0, bg="#FFC107")
btn_20.place(x=500, y=250)
btn_21 = Button(root, image=number_21, command=choose_number, borderwidth=0, highlightthickness=0, highlightbackground="#FFC107", bd=0, bg="#FFC107")
btn_21.place(x=50, y=300)
btn_22 = Button(root, image=number_22, command=choose_number, borderwidth=0, highlightthickness=0, highlightbackground="#FFC107", bd=0, bg="#FFC107")
btn_22.place(x=100, y=300)
btn_23 = Button(root, image=number_23, command=choose_number, borderwidth=0, highlightthickness=0, highlightbackground="#FFC107", bd=0, bg="#FFC107")
btn_23.place(x=150, y=300)
btn_24 = Button(root, image=number_24, command=choose_number, borderwidth=0, highlightthickness=0, highlightbackground="#FFC107", bd=0, bg="#FFC107")
btn_24.place(x=200, y=300)
btn_25 = Button(root, image=number_25, command=choose_number, borderwidth=0, highlightthickness=0, highlightbackground="#FFC107", bd=0, bg="#FFC107")
btn_25.place(x=250, y=300)
btn_26 = Button(root, image=number_26, command=choose_number, borderwidth=0, highlightthickness=0, highlightbackground="#FFC107", bd=0, bg="#FFC107")
btn_26.place(x=300, y=300)
btn_27 = Button(root, image=number_27, command=choose_number, borderwidth=0, highlightthickness=0, highlightbackground="#FFC107", bd=0, bg="#FFC107")
btn_27.place(x=350, y=300)
btn_28 = Button(root, image=number_28, command=choose_number, borderwidth=0, highlightthickness=0, highlightbackground="#FFC107", bd=0, bg="#FFC107")
btn_28.place(x=400, y=300)
btn_29 = Button(root, image=number_29, command=choose_number, borderwidth=0, highlightthickness=0, highlightbackground="#FFC107", bd=0, bg="#FFC107")
btn_29.place(x=450, y=300)
btn_30 = Button(root, image=number_30, command=choose_number, borderwidth=0, highlightthickness=0, highlightbackground="#FFC107", bd=0, bg="#FFC107")
btn_30.place(x=500, y=300)

my_label = Label(root, text="")
my_label.place(x=50, y=450)


root.mainloop()
