from tkinter import *


root = Tk()
root.geometry("600x600")
root.title("LOTTO GAME")
root.config(bg="#FFC107")

number_1 = PhotoImage(file="images/buttons/1.png")
number_2 = PhotoImage(file="images/buttons/2.png")
number_3 = PhotoImage(file="images/buttons/3.png")
number_4 = PhotoImage(file="images/buttons/4.png")
number_5 = PhotoImage(file="images/buttons/5.png")
number_6 = PhotoImage(file="images/buttons/6.png")
number_7 = PhotoImage(file="images/buttons/7.png")
number_8 = PhotoImage(file="images/buttons/8.png")
number_9 = PhotoImage(file="images/buttons/9.png")
number_10 = PhotoImage(file="images/buttons/10.png")
number_11 = PhotoImage(file="images/buttons/11.png")
number_12 = PhotoImage(file="images/buttons/12.png")
number_13 = PhotoImage(file="images/buttons/13.png")
number_14 = PhotoImage(file="images/buttons/14.png")
number_15 = PhotoImage(file="images/buttons/15.png")
number_16 = PhotoImage(file="images/buttons/16.png")

numb_label = Label(image=number_1)


def choose_number():
    my_label.config(text="1")


btn_1 = Button(root, image=number_1, command=choose_number, borderwidth=0, highlightthickness=0, highlightbackground="#FFC107", bd=0, bg="#FFC107")
btn_1.place(x=50, y=150)
btn_2 = Button(root, image=number_2, command=choose_number, borderwidth=0, highlightthickness=0, highlightbackground="#FFC107", bd=0, bg="#FFC107")
btn_2.place(x=100, y=150)
btn_3 = Button(root, image=number_3, command=choose_number, borderwidth=0, highlightthickness=0, highlightbackground="#FFC107", bd=0, bg="#FFC107")
btn_3.place(x=150, y=150)
btn_4 = Button(root, image=number_4, command=choose_number, borderwidth=0, highlightthickness=0, highlightbackground="#FFC107", bd=0, bg="#FFC107")
btn_4.place(x=200, y=150)
btn_5 = Button(root, image=number_5, command=choose_number, borderwidth=0, highlightthickness=0, highlightbackground="#FFC107", bd=0, bg="#FFC107")
btn_5.place(x=250, y=150)
btn_6 = Button(root, image=number_6, command=choose_number, borderwidth=0, highlightthickness=0, highlightbackground="#FFC107", bd=0, bg="#FFC107")
btn_6.place(x=300, y=150)
btn_7 = Button(root, image=number_7, command=choose_number, borderwidth=0, highlightthickness=0, highlightbackground="#FFC107", bd=0, bg="#FFC107")
btn_7.place(x=350, y=150)
btn_8 = Button(root, image=number_8, command=choose_number, borderwidth=0, highlightthickness=0, highlightbackground="#FFC107", bd=0, bg="#FFC107")
btn_8.place(x=400, y=150)
btn_9 = Button(root, image=number_9, command=choose_number, borderwidth=0, highlightthickness=0, highlightbackground="#FFC107", bd=0, bg="#FFC107")
btn_9.place(x=450, y=150)
btn_10 = Button(root, image=number_10, command=choose_number, borderwidth=0, highlightthickness=0, highlightbackground="#FFC107", bd=0, bg="#FFC107")
btn_10.place(x=500, y=150)
btn_11 = Button(root, image=number_11, command=choose_number, borderwidth=0, highlightthickness=0, highlightbackground="#FFC107", bd=0, bg="#FFC107")
btn_11.place(x=50, y=200)
btn_12 = Button(root, image=number_12, command=choose_number, borderwidth=0, highlightthickness=0, highlightbackground="#FFC107", bd=0, bg="#FFC107")
btn_12.place(x=100, y=200)
btn_13 = Button(root, image=number_13, command=choose_number, borderwidth=0, highlightthickness=0, highlightbackground="#FFC107", bd=0, bg="#FFC107")
btn_13.place(x=150, y=200)
btn_14 = Button(root, image=number_14, command=choose_number, borderwidth=0, highlightthickness=0, highlightbackground="#FFC107", bd=0, bg="#FFC107")
btn_14.place(x=200, y=200)
btn_15 = Button(root, image=number_15, command=choose_number, borderwidth=0, highlightthickness=0, highlightbackground="#FFC107", bd=0, bg="#FFC107")
btn_15.place(x=250, y=200)
btn_16 = Button(root, image=number_16, command=choose_number, borderwidth=0, highlightthickness=0, highlightbackground="#FFC107", bd=0, bg="#FFC107")
btn_16.place(x=300, y=200)

my_label = Label(root, text="")
my_label.place(x=50, y=250)


root.mainloop()
